[package]
name = "helloworld"
version = "0.1.0"
edition = "2024"


[dependencies]
mio = { git = "https://github.com/carllerche/mio" }
chrono = "0.4.40"
clap = { version="4.5.35", features = ["derive"]}